apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-pod
  namespace: devops-tools
  labels:
    app: flask-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-service
  template:
    metadata:
      labels:
        app: flask-service
    spec:
      containers:
      - name: flask-test-contianer
        image: tavarescruz/service-flask:52-1d2e501001fb3ae7760c34ca54d865dccf5ac65b
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000