apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  namespace: devops-tools
spec:
  containers:
  - name: flask-app-pod
    image: tavarescruz/service-flask:20-e5db05c1f35a4c5d64690f8754fc9e35f4ee514d
    ports:
    - containerPort: 5000