apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  namespace: devops-tools
spec:
  containers:
  - name: flask-app-pod
    image: tavarescruz/python-flask:latest
    ports:
    - containerPort: 5000