apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  namespace: devops-tools
spec:
  containers:
  - name: flask-app-pod
    image: tavarescruz/service-flask:55-31b2d201ec45d7c215eca5f8e0022e5df63ae437
    ports:
    - containerPort: 5000